export const YOUR_COLLECTION = {
  owned: [
    "House of Bo Bonbon", "House of Bo Infinitoud", "Yellowstone Tornado Tru Western",
    "Heretic Nosferatu", "Strength in Santal — Scents of Wood", "Plum in Cognac — Scents of Wood",
    "Ceremonia Perfume de la Tierra", "34 Boulevard Saint Germain — Diptyque",
    "Santal Greenery — Dries Van Noten", "Eau Legendaire Reserve En Afrique 1934",
    "Rock the Myrrh — Dries Van Noten", "Libre Flowers and Flames — YSL",
    "Libre Berry — YSL", "Corail Oscuro — Diptyque", "Beach Blossom — Jo Malone", "Cult Gaia Mast",
  ],
  had: ["House of Bo Espiritu", "Phluid Project Intention"],
  want: [
    "Voodoo Chile — Dries Van Noten", "Casa Blanca — House of Bo", "Philosykos — Diptyque",
    "Etat Libre d'Orange Frustration", "Memo Paris French Leather", "Eau Capitale — Diptyque",
    "Camomile Satin — Dries Van Noten", "Fleur Du Mal — Dries Van Noten",
    "Jazz Club — Maison Martin Margiela", "By the Fireplace — Maison Martin Margiela",
    "Crazy Basil — Dries Van Noten",
  ],
  wantToTry: [
    "Guilty Story — Mihan Aromatics", "Ave Maria — House of Bo", "Rosario — House of Bo",
    "Gardenia Petale — Van Cleef and Arpels", "Gong — Floraiku",
    "Poets of Berlin — Vilhelm Parfumerie", "Naked Dance — Oddity", "Insolence — Guerlain",
    "Bois Farine — L'Artisan Parfumeur", "Eau de Sens — Diptyque", "Wild Vetiver — Creed",
    "Taormina Orange — Tom Ford", "Brutus — Orto Parisi", "Unknown Pleasures — Kerosene",
    "Orpheon — Diptyque", "Calahorra — Woha Parfums", "Myrrh and Tonka — Jo Malone",
    "Velvet Rose and Oud — Jo Malone", "Scarlet Poppy Intense — Jo Malone",
  ],
};

export const INITIAL_BOTTLES = [
  { name: "Bonbon",              fullName: "House of Bo Bonbon",                        house: "House of Bo",               cost: 165, ml: 50,  freq: 6, status: "owned" },
  { name: "Infinitoud",          fullName: "House of Bo Infinitoud",                    house: "House of Bo",               cost: 185, ml: 50,  freq: 7, status: "owned" },
  { name: "Nosferatu",           fullName: "Heretic Nosferatu",                         house: "Heretic",                   cost: 165, ml: 50,  freq: 8, status: "owned" },
  { name: "Strength in Santal",  fullName: "Strength in Santal — Scents of Wood",      house: "Scents of Wood",            cost: 195, ml: 50,  freq: 7, status: "owned" },
  { name: "Plum in Cognac",      fullName: "Plum in Cognac — Scents of Wood",          house: "Scents of Wood",            cost: 195, ml: 50,  freq: 5, status: "owned" },
  { name: "Perfume de la Tierra",fullName: "Ceremonia Perfume de la Tierra",            house: "Ceremonia",                 cost: 68,  ml: 50,  freq: 6, status: "owned" },
  { name: "34 Blvd St Germain",  fullName: "34 Boulevard Saint Germain — Diptyque",     house: "Diptyque",                  cost: 180, ml: 75,  freq: 5, status: "owned" },
  { name: "Santal Greenery",     fullName: "Santal Greenery — Dries Van Noten",        house: "Dries Van Noten",           cost: 250, ml: 100, freq: 8, status: "owned" },
  { name: "Reserve En Afrique",  fullName: "Eau Legendaire Reserve En Afrique 1934",   house: "Eau Legendaire",            cost: 220, ml: 100, freq: 4, status: "owned" },
  { name: "Rock the Myrrh",      fullName: "Rock the Myrrh — Dries Van Noten",         house: "Dries Van Noten",           cost: 250, ml: 100, freq: 6, status: "owned" },
  { name: "Libre Flowers&Flames",fullName: "Libre Flowers and Flames — YSL",           house: "YSL",                       cost: 150, ml: 90,  freq: 7, status: "owned" },
  { name: "Libre Berry",         fullName: "Libre Berry — YSL",                        house: "YSL",                       cost: 140, ml: 50,  freq: 5, status: "owned" },
  { name: "Corail Oscuro",       fullName: "Corail Oscuro — Diptyque",                 house: "Diptyque",                  cost: 200, ml: 75,  freq: 4, status: "owned" },
  { name: "Beach Blossom",       fullName: "Beach Blossom — Jo Malone",                house: "Jo Malone",                 cost: 78,  ml: 30,  freq: 3, status: "owned" },
  { name: "Cult Gaia Mast",      fullName: "Cult Gaia Mast",                           house: "Cult Gaia",                 cost: 95,  ml: 50,  freq: 5, status: "owned" },
  { name: "Tornado Tru Western", fullName: "Yellowstone Tornado Tru Western",          house: "Yellowstone",               cost: 130, ml: 50,  freq: 4, status: "owned" },
  { name: "Espiritu",            fullName: "House of Bo Espiritu",                     house: "House of Bo",               cost: 165, ml: 50,  freq: 0, status: "had" },
  { name: "Intention",           fullName: "Phluid Project Intention",                 house: "Phluid Project",            cost: 90,  ml: 50,  freq: 0, status: "had" },
  { name: "Voodoo Chile",        fullName: "Voodoo Chile — Dries Van Noten",           house: "Dries Van Noten",           cost: 250, ml: 100, freq: 0, status: "want" },
  { name: "Casa Blanca",         fullName: "Casa Blanca — House of Bo",                house: "House of Bo",               cost: 185, ml: 50,  freq: 0, status: "want" },
  { name: "Philosykos",          fullName: "Philosykos — Diptyque",                    house: "Diptyque",                  cost: 180, ml: 75,  freq: 0, status: "want" },
  { name: "Frustration",         fullName: "Etat Libre d'Orange Frustration",          house: "Etat Libre d'Orange",       cost: 155, ml: 50,  freq: 0, status: "want" },
  { name: "French Leather",      fullName: "Memo Paris French Leather",                house: "Memo Paris",                cost: 295, ml: 75,  freq: 0, status: "want" },
  { name: "Eau Capitale",        fullName: "Eau Capitale — Diptyque",                  house: "Diptyque",                  cost: 180, ml: 75,  freq: 0, status: "want" },
  { name: "Camomile Satin",      fullName: "Camomile Satin — Dries Van Noten",         house: "Dries Van Noten",           cost: 250, ml: 100, freq: 0, status: "want" },
  { name: "Fleur Du Mal",        fullName: "Fleur Du Mal — Dries Van Noten",           house: "Dries Van Noten",           cost: 250, ml: 100, freq: 0, status: "want" },
  { name: "Jazz Club",           fullName: "Jazz Club — Maison Martin Margiela",       house: "Maison Martin Margiela",    cost: 140, ml: 100, freq: 0, status: "want" },
  { name: "By the Fireplace",    fullName: "By the Fireplace — Maison Martin Margiela",house: "Maison Martin Margiela",    cost: 140, ml: 100, freq: 0, status: "want" },
  { name: "Crazy Basil",         fullName: "Crazy Basil — Dries Van Noten",            house: "Dries Van Noten",           cost: 250, ml: 100, freq: 0, status: "want" },
  { name: "Guilty Story",        fullName: "Guilty Story — Mihan Aromatics",           house: "Mihan Aromatics",           cost: 200, ml: 50,  freq: 0, status: "want to try" },
  { name: "Ave Maria",           fullName: "Ave Maria — House of Bo",                  house: "House of Bo",               cost: 185, ml: 50,  freq: 0, status: "want to try" },
  { name: "Rosario",             fullName: "Rosario — House of Bo",                    house: "House of Bo",               cost: 185, ml: 50,  freq: 0, status: "want to try" },
  { name: "Poets of Berlin",     fullName: "Poets of Berlin — Vilhelm Parfumerie",     house: "Vilhelm Parfumerie",        cost: 245, ml: 100, freq: 0, status: "want to try" },
  { name: "Myrrh and Tonka",     fullName: "Myrrh and Tonka — Jo Malone",              house: "Jo Malone",                 cost: 78,  ml: 50,  freq: 0, status: "want to try" },
  { name: "Velvet Rose & Oud",   fullName: "Velvet Rose and Oud — Jo Malone",          house: "Jo Malone",                 cost: 150, ml: 50,  freq: 0, status: "want to try" },
  { name: "Orpheon",             fullName: "Orpheon — Diptyque",                       house: "Diptyque",                  cost: 180, ml: 75,  freq: 0, status: "want to try" },
];
